# Generated by Django 2.0.9 on 2019-02-12 06:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0055_auto_20190212_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=35, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=35, verbose_name='Last Name')),
                ('suffix', models.CharField(max_length=10, verbose_name='Suffix')),
                ('title', models.CharField(choices=[('mr', 'MR'), ('ms', 'MS')], max_length=10, verbose_name='Title')),
                ('phone1', models.BigIntegerField(verbose_name='Phone')),
                ('phone2', models.BigIntegerField(default=None, verbose_name='Another Phone')),
                ('mobile1', models.BigIntegerField(verbose_name='Mobile')),
                ('mobile2', models.BigIntegerField(default=None, verbose_name='Another Mobile')),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.IntegerField(default=None, verbose_name='Fax')),
            ],
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30, verbose_name='Company Name')),
                ('companyAddress', models.CharField(max_length=50, verbose_name='Company Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postalCode', models.IntegerField(verbose_name='Postal Code')),
                ('companyPhone', models.IntegerField(verbose_name='Company Phone')),
                ('companyFax', models.IntegerField(verbose_name='Company Fax')),
                ('buyer', models.BooleanField(default=None, editable=False, verbose_name='Is Buyer')),
                ('supplier', models.BooleanField(default=None, editable=False, verbose_name='Is Supplier')),
                ('website', models.URLField(default=None, verbose_name='Website')),
                ('elementaryID', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.elementaryhead', verbose_name='Elementary head')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.suppliers', verbose_name='Company'),
        ),
    ]
