# Generated by Django 2.0.9 on 2019-02-08 06:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0046_auto_20190208_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30, verbose_name='Company Name')),
                ('contactPersonName', models.CharField(max_length=30, verbose_name='Contact Person Name')),
                ('companyAddress', models.CharField(max_length=50, verbose_name='Company Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postalCode', models.IntegerField(verbose_name='Postal Code')),
                ('companyPhone', models.IntegerField(verbose_name='Company Phone')),
                ('companyFax', models.IntegerField(verbose_name='Company Fax')),
                ('buyer', models.BooleanField(default=False, verbose_name='Is Buyer')),
                ('supplier', models.BooleanField(default=False, verbose_name='Is Supplier')),
                ('elementaryID', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.elementaryhead', verbose_name='Elementary head')),
            ],
        ),
    ]
