# Generated by Django 2.0.9 on 2019-02-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=35, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=35, verbose_name='Last Name')),
                ('suffix', models.CharField(max_length=10, verbose_name='Suffix')),
                ('title', models.CharField(choices=[('mr', 'MR'), ('ms', 'MS')], max_length=10, verbose_name='Title')),
                ('phone1', models.IntegerField(verbose_name='Phone')),
                ('phone2', models.IntegerField(default=None, verbose_name='Another Phone')),
                ('mobile1', models.IntegerField(default=None, verbose_name='Another Mobile')),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.IntegerField(default=None, verbose_name='Fax')),
            ],
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='brands',
        ),
        migrations.DeleteModel(
            name='counts',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contactPersonName',
        ),
        migrations.AddField(
            model_name='users',
            name='website',
            field=models.URLField(default=False, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.users', verbose_name='Company'),
        ),
    ]
