# Generated by Django 2.0.9 on 2019-02-12 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightPerBag', models.IntegerField(verbose_name='Weight Per Bag')),
                ('conesPerBag', models.IntegerField(verbose_name='Cones Per Bag')),
                ('weightPerCone', models.IntegerField(verbose_name='Weight Per Cone')),
                ('noOfBags', models.IntegerField(verbose_name='No of Bags')),
                ('noOfAdditional', models.IntegerField(verbose_name='No of Additional Cones')),
            ],
        ),
        migrations.AddField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 12, 9, 30, 28, 326493), editable=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='endDate',
            field=models.DateField(default=None, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='incomeTax',
            field=models.IntegerField(default=None, verbose_name='Income Tax'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='manulContractNumber',
            field=models.IntegerField(default=None, verbose_name='Manul Contract Number'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='paymentDays',
            field=models.IntegerField(default=None, verbose_name='Payment Days'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='productDetailID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.productDetails', verbose_name='Select Product'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='ratePerUnit',
            field=models.IntegerField(default=None, editable=False, verbose_name='Rate Per Unit'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='remarks',
            field=models.CharField(default=None, max_length=100, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='saleTax',
            field=models.IntegerField(default=None, verbose_name='Sale Tax'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='saleTaxwithHeld',
            field=models.IntegerField(default=None, verbose_name='Sale Tax with Held'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='startDate',
            field=models.DateField(default=None, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='supplierID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Purchase.suppliers', verbose_name='Select Supplier'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='totalUnits',
            field=models.IntegerField(default=None, editable=False, verbose_name='Total Units'),
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.contracts', verbose_name='Select Contract'),
        ),
    ]
