# Generated by Django 2.0.9 on 2019-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_auto_20190208_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='website',
            field=models.URLField(default=None, verbose_name='Website'),
        ),
    ]
