# Generated by Django 2.0.9 on 2019-02-12 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_auto_20190212_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 12, 9, 31, 31, 490934), editable=False),
        ),
    ]
