# Generated by Django 2.0.9 on 2019-02-12 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_auto_20190212_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 12, 9, 55, 38, 571136), editable=False),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='ratePerUnit',
            field=models.IntegerField(default=None, verbose_name='Rate Per Unit'),
        ),
    ]
