# Generated by Django 2.0.9 on 2019-02-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_auto_20190208_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile1',
            field=models.BigIntegerField(verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile2',
            field=models.BigIntegerField(default=None, verbose_name='Another Mobile'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone1',
            field=models.BigIntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone2',
            field=models.BigIntegerField(default=None, verbose_name='Another Phone'),
        ),
    ]
