# Generated by Django 2.0.9 on 2019-02-13 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_auto_20190213_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 5, 12, 11, 139342), editable=False),
        ),
    ]
