# Generated by Django 2.0.9 on 2019-02-13 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_auto_20190213_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 10, 9, 36, 458426), editable=False),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='productDetailID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Inventory.productDetails', verbose_name='Select Product'),
        ),
    ]
