# Generated by Django 2.0.9 on 2019-02-14 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0009_auto_20190214_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='addInventory',
            field=models.BooleanField(default=0, verbose_name='Do you want to add starting Inventory for this product'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 5, 54, 10, 941826), editable=False),
        ),
    ]
