# Generated by Django 2.0.9 on 2019-02-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0012_auto_20190214_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='addInventory',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 7, 38, 21, 179822), editable=False),
        ),
    ]
