# Generated by Django 2.0.9 on 2019-02-21 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0018_auto_20190219_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 6, 17, 19, 805162), editable=False),
        ),
    ]
