# Generated by Django 2.0.9 on 2019-01-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subheads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.heads')),
            ],
        ),
    ]
