# Generated by Django 2.0.9 on 2019-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_subheads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subheads',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
