# Generated by Django 2.0.9 on 2019-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20190121_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subheads',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
