# Generated by Django 2.0.9 on 2019-01-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20190121_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='elementaryhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.heads')),
                ('subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.subheads')),
            ],
        ),
    ]
