# Generated by Django 2.0.9 on 2019-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_elementaryhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementaryhead',
            name='code',
            field=models.CharField(default=None, editable=False, max_length=15),
        ),
    ]
