# Generated by Django 2.0.9 on 2019-01-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20190124_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
