# Generated by Django 2.0.9 on 2019-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20190125_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
