# Generated by Django 2.0.9 on 2019-01-28 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_auto_20190128_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 7, 52, 49, 941727)),
        ),
        migrations.AlterField(
            model_name='heads',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
