# Generated by Django 2.0.9 on 2019-01-29 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0032_auto_20190129_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 8, 7, 19, 156675)),
        ),
    ]
