# Generated by Django 2.0.9 on 2019-01-29 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_auto_20190129_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='accounts',
            name='debit',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 9, 29, 7, 235363)),
        ),
    ]
