# Generated by Django 2.0.9 on 2019-01-30 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_auto_20190129_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementaryhead',
            name='left',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='elementaryhead',
            name='right',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 4, 53, 59, 917754)),
        ),
    ]
