# Generated by Django 2.0.9 on 2019-01-30 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0037_auto_20190130_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 5, 41, 18, 378698)),
        ),
    ]
