# Generated by Django 2.0.9 on 2019-01-30 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0038_auto_20190130_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 10, 24, 27, 187030)),
        ),
    ]
