# Generated by Django 2.0.9 on 2019-01-31 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0039_auto_20190130_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 11, 7, 53, 473824)),
        ),
    ]
