# Generated by Django 2.0.9 on 2019-01-31 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0040_auto_20190131_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 11, 8, 30, 952983)),
        ),
    ]
