# Generated by Django 2.0.9 on 2019-02-01 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0041_auto_20190131_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 5, 13, 29, 781814)),
        ),
    ]
