# Generated by Django 2.0.9 on 2019-02-07 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0042_auto_20190201_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('contactPersonName', models.CharField(max_length=30)),
                ('companyAddress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postalCode', models.IntegerField()),
                ('companyPhone', models.IntegerField()),
                ('companyFax', models.IntegerField()),
                ('buyer', models.BooleanField(default=False)),
                ('supplier', models.BooleanField(default=False)),
                ('elementaryID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.elementaryhead')),
            ],
        ),
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 6, 48, 20, 530989)),
        ),
    ]
