# Generated by Django 2.0.9 on 2019-02-08 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0044_auto_20190207_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='brands',
        ),
        migrations.DeleteModel(
            name='counts',
        ),
        migrations.RemoveField(
            model_name='users',
            name='elementaryID',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 6, 6, 56, 614955)),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
