# Generated by Django 2.0.9 on 2019-02-08 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0046_auto_20190208_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 11, 21, 20, 727757)),
        ),
    ]
