# Generated by Django 2.0.9 on 2019-02-08 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0049_auto_20190208_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 11, 26, 26, 178565)),
        ),
    ]
