# Generated by Django 2.0.9 on 2019-02-08 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0050_auto_20190208_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 11, 37, 47, 52868)),
        ),
    ]
