# Generated by Django 2.0.9 on 2019-02-13 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0060_auto_20190212_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 4, 55, 39, 916247)),
        ),
    ]
