# Generated by Django 2.0.9 on 2019-02-14 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0063_auto_20190213_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 5, 19, 33, 985595)),
        ),
    ]
