# Generated by Django 2.0.9 on 2019-02-14 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0064_auto_20190214_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 5, 34, 22, 726774)),
        ),
    ]
