# Generated by Django 2.0.9 on 2019-02-14 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0015_auto_20190214_1114'),
        ('Accounts', '0070_auto_20190214_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chequeNo', models.IntegerField(max_length=20, verbose_name='Cheque No')),
                ('chequeImage', models.ImageField(upload_to='assets/images/%Y/%m/%d', verbose_name='Cheque Image')),
                ('depositNo', models.IntegerField(max_length=20, verbose_name='Deposit No')),
                ('depositImage', models.ImageField(upload_to='assets/images/%Y/%m/%d')),
                ('totalunits', models.IntegerField(verbose_name='Total Units')),
                ('dateOfentry', models.DateField(default=datetime.datetime(2019, 2, 14, 11, 14, 26, 729136))),
                ('accountID', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Accounts.elementaryhead')),
                ('purchaseContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.contracts', verbose_name='Purchase Contract')),
            ],
        ),
        migrations.CreateModel(
            name='paymentOutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfBags', models.IntegerField()),
                ('noOfAdditionalCone', models.IntegerField()),
                ('paymentOutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.paymentOut')),
            ],
        ),
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 11, 14, 26, 728511)),
        ),
    ]
