# Generated by Django 2.0.9 on 2019-02-21 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0074_auto_20190219_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 6, 17, 19, 785767)),
        ),
        migrations.AlterField(
            model_name='paymentout',
            name='dateOfentry',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 6, 17, 19, 786313)),
        ),
    ]
