# Generated by Django 2.0.9 on 2019-02-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Product Name')),
                ('label', models.CharField(default=None, max_length=50, verbose_name='Product Label')),
                ('partNumber', models.CharField(default=None, max_length=50, verbose_name='Part Number')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.brands', verbose_name='Brand')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.counts', verbose_name='Count')),
            ],
        ),
    ]
