# Generated by Django 2.0.9 on 2019-02-13 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingInventory', models.IntegerField(verbose_name='Starting Inventory')),
                ('startingPrice', models.IntegerField(verbose_name='Starting Price')),
                ('inventoryReceived', models.IntegerField(verbose_name='Inventory Received')),
                ('inventoryShipped', models.IntegerField(verbose_name='Inventory Shipped')),
                ('currentInventory', models.IntegerField(verbose_name='Current Inventory')),
                ('currentPrice', models.IntegerField(verbose_name='Current Price')),
                ('minimumRequired', models.IntegerField(verbose_name='Minimum Required')),
                ('dateModified', models.DateTimeField(default=datetime.datetime(2019, 2, 13, 10, 9, 36, 438679))),
                ('productDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.productDetails')),
            ],
        ),
    ]
