# Generated by Django 2.0.9 on 2019-02-14 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='addInventory',
            field=models.BooleanField(default=0, verbose_name='Do you want to add starting Inventory for this product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 5, 19, 33, 990234)),
        ),
    ]
