# Generated by Django 2.0.9 on 2019-02-14 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20190214_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='addInventory',
        ),
        migrations.AlterField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 5, 34, 22, 731060)),
        ),
    ]
