# Generated by Django 2.0.9 on 2019-02-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20190214_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='addInventory',
            field=models.BooleanField(default=False, verbose_name='Do you want to add starting Inventory for this product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 7, 38, 21, 162231)),
        ),
    ]
