# Generated by Django 2.0.9 on 2019-02-14 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0014_auto_20190214_1058'),
        ('Inventory', '0008_auto_20190214_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventoryIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitsIn', models.IntegerField(verbose_name='Units In')),
                ('doID', models.IntegerField(verbose_name='Do ID')),
                ('doImage', models.ImageField(upload_to='inventoryIn/%Y/%m/%d')),
                ('invoiceID', models.IntegerField(verbose_name='Invoice ID')),
                ('invoiceImage', models.ImageField(upload_to='inventoryIn/%Y/%m/%d')),
                ('agingDate', models.DateField()),
                ('dateOfEntry', models.DateField(default=datetime.datetime(2019, 2, 14, 10, 58, 23, 499128))),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 10, 58, 23, 498444)),
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products'),
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='purchaseContractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.contracts'),
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.suppliers', verbose_name='Supplier'),
        ),
    ]
