# Generated by Django 2.0.9 on 2019-02-14 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0016_auto_20190214_1159'),
        ('Inventory', '0010_auto_20190214_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Purchase.contracts')),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryin',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 11, 59, 8, 60797)),
        ),
        migrations.AlterField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 11, 59, 8, 60124)),
        ),
    ]
