# Generated by Django 2.0.9 on 2019-02-19 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20190218_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addinventory',
            name='contractID',
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='doType',
            field=models.CharField(blank=True, choices=[('orginal', 'ORGINAL'), ('dummy', 'DUMMY')], max_length=20, verbose_name='Select DO Type'),
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='enterPaymentDays',
            field=models.IntegerField(blank=True, default=None, verbose_name='Enter Payment Days'),
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='labReportImage',
            field=models.ImageField(blank=True, upload_to='assets/image/%Y/%m/%d', verbose_name='Lab Report Image'),
        ),
        migrations.AlterField(
            model_name='inventoryin',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 19, 6, 31, 43, 552078)),
        ),
        migrations.AlterField(
            model_name='inventoryin',
            name='unitsIn',
            field=models.IntegerField(verbose_name='Enter No of Bags'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 6, 31, 43, 551549)),
        ),
        migrations.DeleteModel(
            name='AddInventory',
        ),
        migrations.CreateModel(
            name='AddInventory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('Inventory.inventoryin',),
        ),
    ]
