# Generated by Django 2.0.9 on 2019-02-13 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_products'),
        ('Accounts', '0063_auto_20190213_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=35, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=35, verbose_name='Last Name')),
                ('suffix', models.CharField(max_length=10, verbose_name='Suffix')),
                ('title', models.CharField(choices=[('mr', 'MR'), ('ms', 'MS')], max_length=10, verbose_name='Title')),
                ('phone1', models.BigIntegerField(verbose_name='Phone')),
                ('phone2', models.BigIntegerField(default=None, verbose_name='Another Phone')),
                ('mobile1', models.BigIntegerField(verbose_name='Mobile')),
                ('mobile2', models.BigIntegerField(default=None, verbose_name='Another Mobile')),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.IntegerField(default=None, verbose_name='Fax')),
            ],
        ),
        migrations.CreateModel(
            name='contractDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightPerBag', models.IntegerField(verbose_name='Weight Per Bag')),
                ('conesPerBag', models.IntegerField(verbose_name='Cones Per Bag')),
                ('weightPerCone', models.IntegerField(verbose_name='Weight Per Cone')),
                ('noOfBags', models.IntegerField(verbose_name='No of Bags')),
                ('noOfAdditional', models.IntegerField(verbose_name='No of Additional Cones')),
            ],
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalUnits', models.IntegerField(default=None, editable=False, verbose_name='Total Units')),
                ('ratePerUnit', models.IntegerField(default=None, verbose_name='Rate Per Unit')),
                ('saleTax', models.IntegerField(default=None, verbose_name='Sale Tax')),
                ('incomeTax', models.IntegerField(default=None, verbose_name='Income Tax')),
                ('saleTaxwithHeld', models.IntegerField(default=None, verbose_name='Sale Tax with Held')),
                ('startDate', models.DateField(default=None, verbose_name='Start Date')),
                ('endDate', models.DateField(default=None, verbose_name='End Date')),
                ('manulContractNumber', models.IntegerField(default=None, verbose_name='Manul Contract Number')),
                ('paymentDays', models.IntegerField(default=None, verbose_name='Payment Days')),
                ('remarks', models.CharField(default=None, max_length=100, verbose_name='Remarks')),
                ('dateOfEntry', models.DateField(default=datetime.datetime(2019, 2, 13, 10, 9, 36, 462729), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30, verbose_name='Company Name')),
                ('companyAddress', models.CharField(max_length=50, verbose_name='Company Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postalCode', models.IntegerField(verbose_name='Postal Code')),
                ('companyPhone', models.IntegerField(verbose_name='Company Phone')),
                ('companyFax', models.IntegerField(verbose_name='Company Fax')),
                ('buyer', models.BooleanField(default=None, editable=False, verbose_name='Is Buyer')),
                ('supplier', models.BooleanField(default=None, editable=False, verbose_name='Is Supplier')),
                ('website', models.URLField(default=None, verbose_name='Website')),
                ('elementaryID', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.elementaryhead', verbose_name='Elementary head')),
            ],
        ),
        migrations.AddField(
            model_name='contracts',
            name='customerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sale.customers', verbose_name='Select Customer'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='productDetailID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Inventory.productDetails', verbose_name='Select Product'),
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sale.contracts', verbose_name='Select Contract'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sale.customers', verbose_name='Customer Company'),
        ),
    ]
