# Generated by Django 2.0.9 on 2019-02-14 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0005_auto_20190214_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 7, 32, 45, 12596), editable=False),
        ),
    ]
