# Generated by Django 2.0.9 on 2019-02-14 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0007_auto_20190214_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 10, 58, 23, 501778), editable=False),
        ),
    ]
