# Generated by Django 2.0.9 on 2019-02-14 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0008_auto_20190214_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 11, 14, 26, 756456), editable=False),
        ),
    ]
