# Generated by Django 2.0.9 on 2019-02-22 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0014_auto_20190222_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='dateOfEntry',
            field=models.DateField(default=datetime.datetime(2019, 2, 22, 6, 31, 50, 486806), editable=False),
        ),
    ]
